In [31]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [32]:
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
labelencoder_x = LabelEncoder()

In [35]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [36]:
labelencoder_x.fit_transform(x[:, 0])

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [37]:
x[:; 0] = labelencoder_x.fit_transform(x[:, 0]) #esto nos va a dar la version traudicda de como van a quedar los paises.

SyntaxError: invalid syntax (<ipython-input-37-e26bdc928a56>, line 1)

In [38]:
x[:, 0] = labelencoder_x.fit_transform(x[:, 0]) #esto nos va a dar la version traudicda de como van a quedar los paises.

In [39]:
print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                        
)

X = np.array(ct.fit_transform(X), dtype=np.float)

NameError: name 'X' is not defined

In [41]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
from sklearn.compose import ColumnTransformer

In [43]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                        
)

In [44]:
X = np.array(ct.fit_transform(X), dtype=np.float)

NameError: name 'X' is not defined

In [45]:
x = np.array(ct.fit_transform(x), dtype=np.float)

<ipython-input-45-03659db33f6b>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(ct.fit_transform(x), dtype=np.float)


In [46]:
from sklearn import preprocessing

In [47]:
le_X = preprocessing.LabelEncoder()

In [49]:
x[:,0] = le_X.fit_transform(x[:,0])